### ISSUE TITLE
Create JS tests for contract functions

### ISSUE THREAD

**Issue by forgetso** [prosopo-io/provider#18]
Test functions in `provider/src/tasks/tasks.ts` by porting and upgrading tests from `protocol/tests/prosopo.test.ts`. Place the tests in `provider/tests/tasks/tasks.test.ts`

Linked issues need tested from JS perspective.

- [x] Provider can stake tokens #3
- [x] Provider can unlock staked tokens, deactivating service #4
- [x] Provider can update service origin and/or fee #13
- [x] Active Provider can register data set on blockchain #6
- [x] Register Provider contact details, service origin, fee, and optionally stake #1
